services:
  trantor2-gateway:
    container_name: trantor2-gateway
    image: nginx:alpine
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf
  mysql:
    image: mariadb:10.3
    container_name: trantor2-mysql
    restart: on-failure
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD:-password}'
    expose:
      - 3306
    ports:
      - '${MYSQL_PORT:-3307}:3306'
    command: --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0
    volumes:
      - ${TRANTOR2_WORKSPACE:-~/.trantor2}/data/${VERSION}/mysql:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:3.2.12
    container_name: trantor2-redis
    restart: on-failure
    expose:
      - 6379
    ports:
      - '${REDIS_PORT:-6380}:6379'
    command: --requirepass "password"
#  minio:
#    image: minio/minio:latest
#    container_name: trantor2-minio
#    restart: on-failure
#    environment:
#      MINIO_ROOT_USER: '${OSS_ACCESS_KEY_ID:-x}'
#      MINIO_ROOT_PASSWORD: '${OSS_ACCESS_KEY_SECRET:-placeholder}'
#    command: server /data
#    volumes:
#      - ${TRANTOR2_WORKSPACE:-~/.trantor2}/data/minio:/data
#    ports:
#      - '${MINIO_PORT:-9000}:9000'
#    expose:
#      - 9000
